### PR TITLE
Update to include faction requirements.

### PR DESCRIPTION
**Pull request by noudess**
@joligario If you guys don't have plugin::reject_say() let me know.  It randomly picks one of the standard rejection messages.  I verified these on live.

### CODE REVIEW

**Comment by noudess** [comment]
I also added code to make the new NPC spawn facing the client that turned in the item.  Can delete that if you don't want the color.

This is just a "hey if you want this" - I maintain separate quests on Rolath.

**Review by fryguy503 — APPROVED** [review]
LGTM

**Comment by fryguy503** [comment]
> @joligario If you guys don't have plugin::reject_say() let me know. It randomly picks one of the standard rejection messages. I verified these on live.

I don't see the reject_say() plugin, are you able to include that?

**Comment by noudess** [comment]
Added the plugins.

**Pull request merged**
