### PR TITLE
Update illusion_tools.pl

### PR DESCRIPTION
**Pull request by xXxWarAngelxXx**
Discovered that the switch caused the script to malfunction. I changed it to if statements. Works fine now. First pull for me, please advise if needed, to create better habits. Thank you!

### CODE REVIEW

**Comment by mackal** [comment]
Even if you have the perl switch module installed?

**Comment by joligario** [comment]
Agree with @mackal , should just need perl-switch

**Comment by xXxWarAngelxXx** [comment]
I have to assume I do not have the perl-switch module then. What I have been reading, it is something the perl folks are doing away with. With that being said. The perl-switch module is not part of Akkadius's installer. Where I recieved all my current perl...stuff. Thus the current issue I guess.

**Comment by mackal** [comment]
It should be installing it AFAIK. It's also likely in your package manager as well if you're using Linux.

**Comment by mackal** [comment]
Okay, the module isn't really going away for now, it's just newer perl have their own switch implementation with given/when. It's possible we should switch to this if we decide that we want to up perl req version.

**Comment by Akkadius** [comment]
I never really liked that we had to install a new module to get basic switch functionality in Perl. This is like the only thing we depend on using switch for so I'm totally fine with reverting to simple if statements

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
