### PR TITLE
 Added Talya Darkfall.

### PR DESCRIPTION
**Pull request by xackery**
The tasks are dumped as attachments on the PR. Let me know how we should handle them..

### CODE REVIEW

**Comment by xackery** [comment]
[Scouting the Goblins.txt](https://github.com/ProjectEQ/projecteqquests/files/3214886/Scouting.the.Goblins.txt)
[Lurking in the Shadows.txt](https://github.com/ProjectEQ/projecteqquests/files/3214887/Lurking.in.the.Shadows.txt)
[Lavaspinner Research.txt](https://github.com/ProjectEQ/projecteqquests/files/3214888/Lavaspinner.Research.txt)

**Comment by joligario** [comment]
I would say turn them into SQL INSERTs without ID

**Comment by joligario** [comment]
Ping @xackery

**Comment by xackery** [comment]
I'm in london the next month, and don't have easy access to my PC, will be a bit before I can commit.

**Comment by xackery** [comment]
Feel free to close this if you like. I can do another PR with the changes of DB prep. I'm coding this into my process so it's super easy for me. I also have a lot of other quests that will use the same treatment.

**Pull request closed without merging**
